#include<iostream>
#include<map>
#include"signal_processing.hpp"
#include"channel_remapping.hpp"

// Remaps the channels based on the mapping given to it, this mapping is to be generated
// by computeChannelRemapping() in channel_remapping.hpp
static void remapChannels(std::vector<std::complex<float>> const& signalData,
                   std::map<unsigned, unsigned> const& mapping);

// Performs an inverse polyphase filter bank (PFB) on the signal data, the mapping is required
// for this function so the convolution only goes over the appropriate channels. This mapping
// is provided by computeChannelRemapping() in channel_rempping.hpp
static void performPFB(std::vector<std::complex<float>> const& signalData,
                std::vector<std::complex<float>> const& coefficantPFB,
                std::map<unsigned, unsigned> const& mapping);

// Performs an inverse discrete fourier transorm on the signal data, changing the frequency
// data into a time domain signal
static std::vector<float> performDFT(std::vector<std::complex<float>> const& signalData);


// Downsamples data based on the new sampling rate. This sample rate should be generated by
// computeChannelRemapping()_in channel_remapping.hpp
static void downsampleData(std::vector<float> const& signalData, unsigned samplingRate);

// Converts the downsampled time domain array into a 16bit signed int with clamping
static std::vector<std::int16_t> doPostProcessing(std::vector<float> const& signalData);


std::vector<std::int16_t> processSignal(std::vector<std::complex<float>> const& signalData,
                               std::vector<std::complex<float>> const& coefficiantPFB,
                               ChannelRemapping const& remappingData) {
    std::cout << "ProcessSignal Called" << std::endl;
    remapChannels(signalData, remappingData.channelMap);
    performPFB(signalData, coefficiantPFB, remappingData.channelMap);
    std::vector<float> postDFTSignalData = performDFT(signalData);
    downsampleData(postDFTSignalData, remappingData.newSamplingFreq);
    std::vector<std::int16_t> outData = doPostProcessing(postDFTSignalData);
    return outData;
}

static void remapChannels(std::vector<std::complex<float>> const& signalData,
                   std::map<unsigned, unsigned> const& mapping) {
    std::cout << "remapChannels() called" << std::endl;
}

static void performPFB(std::vector<std::complex<float>> const& signalData,
                std::vector<std::complex<float>> const& coefficantPFB,
                std::map<unsigned, unsigned> const& mapping) {
    std::cout << "performPFB() called" << std::endl;
}

static std::vector<float> performDFT(std::vector<std::complex<float>> const& signalData) {
    std::cout << "performDFT() called" << std::endl;
    return std::vector<float>();
}

static void downsampleData(std::vector<float> const& signalData, unsigned samplingRate) {
    std::cout << "downsampleData() called" << std::endl;
}

static std::vector<std::int16_t> doPostProcessing(std::vector<float> const& signalData) {
    std::cout << "doPostProcessing() called" << std::endl;
    return std::vector<std::int16_t>();
}

